# Generated by Django 6.0.3 on 2026-03-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_answer_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='content',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='chapter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
